import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

// ─── Translations (AR / FR / EN) ─────────────────────────────
const TRANSLATIONS = {
  fr: {
    announcement: "LIVRAISON RAPIDE DANS TOUTES LES WILAYAS & PAIEMENT À LA LIVRAISON",
    nav_new_arrivals: "Nouveautés", nav_collection: "La Collection", nav_about: "À Propos",
    nav_dashboard: "Tableau de Bord", nav_shop_now: "Acheter",
    hero_shop_now: "ACHETER MAINTENANT",
    cat_shop_by: "Acheter par Catégorie", cat_all: "Tout", cat_jeans: "Jeans",
    cat_jackets: "Vestes", cat_hoodies: "Sweats",
    cat_accessories: "Accessoires", cat_shorts: "Shorts", cat_tshirt: "T-shirt", cat_jorts: "Jorts",
    cat_shop_denim: "Shop Denim", cat_shop_jackets: "Shop Vestes", cat_shop_hoodies: "Shop Sweats",
    col_eyebrow: "Nouveautés", col_title: "La Collection", col_view_all: "Voir Tout →",
    col_load_more: "Charger Plus", col_add_to_cart: "Ajouter au Panier",
    about_eyebrow: "Qui nous sommes",
    about_title: "Des objets qui comptent.<br/><em>Des moments qui durent.</em>",
    about_body: "aizo.dz est né d'une conviction que les objets du quotidien doivent être beaux, fonctionnels et intentionnels.",
    nl_eyebrow: "Restez informé",
    nl_title: "Rejoignez le<br/><em>cercle intime.</em>",
    nl_body: "Soyez le premier informé des nouveautés, offres exclusives et histoires derrière chaque pièce.",
    nl_placeholder: "Votre adresse e-mail", nl_subscribe: "S'abonner",
    nl_success: "✓ Merci — vous êtes inscrit.",
    feat_delivery: "Livraison Rapide", feat_delivery_desc: "Livraison rapide et sécurisée à travers toutes les wilayas d'Algérie.",
    feat_auth: "Garantie d'Authenticité", feat_auth_desc: "Chaque produit est vérifié manuellement avant de vous parvenir.",
    feat_returns: "Retours Faciles", feat_returns_desc: "Retours sans tracas sous 14 jours. Sans questions.",
    foot_tagline: "Des essentiels sélectionnés pour une vie plus intentionnelle.<br/>Fièrement Algérien.",
    foot_shop: "Boutique", foot_new_arrivals: "Nouveautés", foot_best_sellers: "Meilleures Ventes",
    foot_home_living: "Maison & Vie", foot_accessories: "Accessoires", foot_gift_sets: "Coffrets Cadeaux",
    foot_info: "Info", foot_our_story: "Notre Histoire", foot_shipping: "Livraison & Retours",
    foot_privacy: "Confidentialité", foot_terms: "Conditions", foot_faq: "FAQ", foot_contact: "Contact",
    foot_copy: "© 2026 AIZO.DZ — Tous droits réservés.", foot_made: "Fait avec intention · Algérie",
    cart_title_ar: "Panier", cart_title_en: "/ Cart",
    cart_empty_ar: "Le panier est vide", cart_empty_en: "Votre panier est vide",
    cart_shop_now: "Acheter Maintenant",
    cart_subtotal: "Sous-total", cart_shipping_label: "Livraison", cart_total: "Total", cart_free: "Gratuite",
    checkout_title_ar: "Informations de Livraison", checkout_title_en: "/ Delivery Info",
    checkout_name_label: "Prénom *", checkout_name_ph: "Votre prénom",
    checkout_surname_label: "Nom *", checkout_surname_ph: "Votre nom",
    checkout_phone_label: "Numéro de Téléphone *", checkout_phone_ph: "05 / 06 / 07 XX XX XX XX",
    checkout_wilaya_label: "Wilaya *", checkout_wilaya_ph: "Choisir la wilaya...",
    checkout_delivery_type: "Type de Livraison *",
    delivery_home: "Livraison à Domicile (A DOMICILE)", delivery_home_desc: "Paiement à la livraison",
    delivery_office: "Livraison au Bureau (STOP DESK)", delivery_office_desc: "Récupération au bureau de livraison",
    checkout_address_label: "Adresse Détaillée *",
    checkout_address_ph: "Ex: Cité la paix, rue de l'émir, n°12, 2ème étage",
    checkout_office_label: "Bureau de Livraison *", checkout_office_ph: "Choisir le bureau...",
    checkout_confirm: "Confirmer la Commande", checkout_sending: "Envoi en cours...",
    err_name: "Veuillez saisir votre prénom", err_surname: "Veuillez saisir votre nom",
    err_phone: "Numéro de téléphone invalide (10 chiffres)", err_wilaya: "Veuillez choisir la wilaya",
    err_address: "Veuillez saisir l'adresse", err_office: "Veuillez choisir le bureau",
    success_title: "Votre commande a été enregistrée !",
    success_subtitle: "Merci pour votre confiance. Nous vous contacterons bientôt pour confirmer la commande.",
    success_order_label: "N° de commande :", success_name_label: "Nom :",
    success_phone_label: "Téléphone :", success_wilaya_label: "Wilaya :",
    success_delivery_label: "Livraison à :", success_total_label: "Total :",
    success_continue: "Continuer les Achats",
    lead_title: "Rejoignez-nous", lead_desc_ar: "Inscrivez-vous à notre newsletter.",
    lead_placeholder: "Votre e-mail", lead_subscribe: "S'inscrire",
    lead_success_title: "Merci !", lead_success_desc: "Votre e-mail a été enregistré.",
    marquee_1: "Qualité Premium", marquee_2: "Livraison Rapide 58 Wilayas",
    marquee_3: "Sélectionné en Algérie", marquee_4: "Mode Consciente",
    marquee_5: "Retours sous 14 Jours", marquee_6: "Authenticité Garantie",
    coll_hero_title: "La Collection", coll_hero_desc: "Des essentiels minimalistes conçus avec précision et intention.",
    coll_search_ph: "Tapez pour rechercher...", coll_categories: "Catégories",
    coll_all: "Tous les Produits", coll_denim: "Denim / Jeans", coll_jackets: "Vestes", coll_hoodies: "Sweats",
    coll_accessories: "Accessoires", coll_shorts: "Shorts", coll_tshirt: "T-shirt", coll_jorts: "Jorts",
    coll_sort: "Trier Par", coll_featured: "En vedette", coll_price_asc: "Prix: Croissant",
    coll_price_desc: "Prix: Décroissant", coll_name_asc: "A-Z", coll_name_desc: "Z-A",
    coll_showing: "Affichage de", coll_products: "produits",
    pick_color: "Choisir la Couleur", pick_size: "Choisir la Taille",
    no_offices: "Aucun bureau disponible dans cette wilaya", choose_office_first: "Veuillez d'abord choisir la wilaya...",
    pd_color: "Couleur", pd_size: "Taille", pd_custom_order: "Commande Personnalisée",
    pd_feat_shipping: "Livraison rapide 58 wilayas", pd_feat_quality: "Qualité premium garantie",
    pd_feat_returns: "Échange ou retour sous 14 jours",
    co_title: "🎨 Personnalisation Premium",
    co_step_design: "Design", co_step_options: "Options", co_step_info: "Infos Client", co_step_summary: "Résumé",
    co_area_center: "Centre poitrine", co_area_chest_left: "Poitrine Gauche", co_area_chest_right: "Poitrine Droite",
    co_area_back: "Dos", co_area_sleeve_right: "Manche Droite", co_area_sleeve_left: "Manche Gauche",
    co_upload: "Uploader", co_delete: "Supprimer", co_garment_color: "Couleur du vêtement",
    co_size: "Taille", co_service_type: "Type de Service", co_embroidery: "Broderie", co_print: "Impression",
    co_active: "Actif", co_coming_soon: "Bientôt",
    co_name: "Prénom *", co_surname: "Nom *", co_email: "Email *", co_phone: "Téléphone *",
    co_province: "Wilaya *", co_notes: "Notes spéciales",
    co_order_summary: "Récapitulatif de la commande", co_product: "Produit",
    co_placements: "Placements", co_customer: "Client",
    co_prev: "← Précédent", co_next: "Suivant →", co_confirm: "✓ Confirmer la commande",
    co_success_title: "Commande envoyée avec succès !", co_success_desc: "Nous avons bien reçu votre commande personnalisée.",
    co_success_close: "Fermer", co_garment_type: "Type de vêtement",
    co_upload_title: "Télécharger vos designs (PNG transparent)", co_drag_drop: "Glissez-déposez vos logos ici",
    co_click_browse: "Ou cliquez pour parcourir les fichiers", co_active_designs: "Mes Designs Actifs",
    co_delivery_info_title: "Informations de livraison", co_name_ph: "Votre prénom", co_surname_ph: "Votre nom",
    co_email_ph: "Ex: email@exemple.com", co_phone_ph: "05 / 06 / 07 XX XX XX XX",
    co_notes_ph: "Instructions spéciales...", co_num_designs: "Nombre de designs",
    co_summary_desc: "Veuillez vérifier les informations ci-dessous avant de soumettre.", reviews: "avis",
    admin_login_title: "Connexion Administrateur", admin_login_desc: "Veuillez saisir le mot de passe.",
    admin_login_pwd_ph: "Mot de passe", admin_login_btn: "Se connecter", admin_back_store: "← Retour à la boutique",
    admin_sidebar_role: "Gestionnaire de boutique", admin_logout: "Se déconnecter",
    admin_nav_stats: "✦ Statistiques", admin_nav_orders: "📦 Commandes",
    admin_nav_custom_orders: "🎨 Commandes Custom", admin_nav_leads: "📧 Liste e-mails",
    admin_nav_add_product: "✨ Ajouter produit", admin_nav_products: "🛍️ Liste produits",
    admin_profile_status: "Admin en ligne", admin_server_disconnected: "Serveur hors ligne",
    admin_login_error: "Le mot de passe est incorrect !",
    admin_back_store_sidebar: "← Retour à la boutique",
    status_pending: "En attente", status_confirmed: "Confirmé", status_ready: "Prêt à expédier",
    status_delivery: "En livraison", status_delivered: "Livré", status_returned: "Retourné", status_cancelled: "Annulé",
    admin_col_order_id: "N° Commande", admin_col_date: "Date", admin_col_customer: "Client",
    admin_col_phone: "Téléphone", admin_col_wilaya: "Wilaya", admin_col_delivery: "Livraison",
    admin_col_items: "Articles", admin_col_total: "Total", admin_col_status: "Statut", admin_col_actions: "Actions",
    admin_col_image: "Image", admin_col_name: "Nom", admin_col_category: "Catégorie", admin_col_price: "Prix",
    admin_col_badge: "Badge", admin_col_rating: "Évaluation", admin_col_sizes: "Tailles", admin_col_source: "Source",
    admin_col_actions_edit: "Modifier", admin_col_actions_delete: "Supprimer",
    admin_products_empty: "Aucun produit chargé.", admin_leads_empty: "Aucun abonné pour le moment.",
    admin_orders_empty: "Aucune commande.", admin_orders_recent_empty: "Aucune commande enregistrée.",
    admin_pagination_prev: "Précédent", admin_pagination_next: "Suivant",
    admin_pagination_page: "Page", admin_pagination_of: "sur",
    admin_form_add_title: "Ajouter un nouveau produit", admin_form_btn_save: "Enregistrer le produit",
    admin_form_btn_update: "Mettre à jour", admin_form_btn_reset: "Réinitialiser",
    admin_form_prod_name: "Nom du produit *", admin_form_prod_name_ph: "Ex: Vescartes Ronin Jacket",
    admin_form_prod_sub: "Description courte *", admin_form_prod_sub_ph: "Ex: Edo collection",
    admin_form_prod_price: "Prix (DZD) *", admin_form_prod_img: "Lien image (URL) *",
    admin_form_prod_badge: "Badge (Optionnel)", admin_form_badge_none: "Aucun badge",
    admin_form_prod_stars: "Étoiles *", admin_form_prod_reviews: "Nb avis *", admin_form_prod_stock: "Stock *",
    admin_form_prod_colors_chk: "Options de couleur ?", admin_form_prod_colors: "Couleurs (séparées par virgules) *",
    admin_form_prod_colors_ph: "Ex: Noir, Blanc, Bleu", admin_form_prod_sizes: "Tailles disponibles *",
    admin_btn_sync: "🔄 Mettre à jour", admin_btn_delete_order: "🗑️ Supprimer",
    admin_btn_ship_zr: "🚀 Expédier via ZR Express", admin_btn_view_mockup: "🎨 Voir le design",
    admin_status_updated: "✓ Statut mis à jour !", admin_order_deleted: "✓ Commande supprimée !",
    admin_product_deleted: "✓ Produit supprimé !", admin_lead_deleted: "✓ Abonné supprimé !",
    admin_order_shipped_zr: "✅ Expédié via ZR Express !",
    admin_order_spec_title: "Détails de la commande personnalisée",
    admin_order_spec_color: "Couleur:", admin_order_spec_size: "Taille:", admin_order_spec_service: "Service:",
    admin_order_spec_client: "Client:", admin_order_spec_email: "E-mail:", admin_order_spec_phone: "Téléphone:",
    admin_order_spec_province: "Wilaya:", admin_order_spec_notes: "Notes:", admin_order_spec_no_notes: "Aucune note",
    admin_order_spec_final_mockup: "Aperçu du modèle final", admin_order_spec_files: "Fichiers joints",
    admin_order_spec_download: "Télécharger le design", admin_order_spec_no_files: "Aucun design joint",
    admin_src_custom: "Ajouté manuellement", admin_src_default: "Par défaut", admin_no_sizes: "Aucune taille",
    admin_confirm_delete_order: "Supprimer définitivement la commande #{id} ?",
    admin_confirm_delete_product: "Supprimer définitivement ce produit ?",
    admin_confirm_delete_lead: "Supprimer cet abonné ? {email}",
    admin_confirm_ship_zr: "Envoyer la commande #{id} à ZR Express ?",
    admin_error_generic: "Une erreur est survenue.",
    admin_sales_total: "Ventes confirmées", admin_orders_total: "Total commandes",
    admin_products_active: "Produits actifs", admin_leads_total: "Total abonnés",
    admin_returned_total: "Commandes retournées", admin_delivered_total: "Commandes livrées",
    admin_recent_orders: "Dernières commandes",
  },
  ar: {
    announcement: "توصيل سريع لـ 58 ولاية والدفع عند الاستلام",
    nav_new_arrivals: "جديدنا", nav_collection: "المجموعة", nav_about: "من نحن",
    nav_dashboard: "لوحة التحكم", nav_shop_now: "تسوق الآن",
    hero_shop_now: "تسوق الآن",
    cat_shop_by: "تسوق حسب الفئة", cat_all: "الكل", cat_jeans: "جينز",
    cat_jackets: "جاكيتات", cat_hoodies: "هوديز",
    cat_accessories: "إكسسوارات", cat_shorts: "شورتات", cat_tshirt: "تي شيرت", cat_jorts: "جورتس",
    cat_shop_denim: "تسوق الجينز", cat_shop_jackets: "تسوق الجاكيتات", cat_shop_hoodies: "تسوق الهوديز",
    col_eyebrow: "جديدنا", col_title: "المجموعة", col_view_all: "عرض الكل ←",
    col_load_more: "تحميل المزيد", col_add_to_cart: "أضف إلى السلة",
    about_eyebrow: "من نحن",
    about_title: "أشياء تهم.<br/><em>لحظات تدوم.</em>",
    about_body: "ولدت aizo.dz من إيمان بأن الأشياء اليومية يجب أن تكون جميلة وعملية ومقصودة.",
    nl_eyebrow: "ابقَ على اطلاع",
    nl_title: "انضم إلى<br/><em>الدائرة الخاصة.</em>",
    nl_body: "كن أول من يعرف عن الوافدين الجدد والعروض الحصرية.",
    nl_placeholder: "بريدك الإلكتروني", nl_subscribe: "اشترك",
    nl_success: "✓ شكراً — أنت مسجل الآن.",
    feat_delivery: "توصيل سريع لـ 58 ولاية", feat_delivery_desc: "توصيل سريع وآمن لكافة الولايات في الجزائر.",
    feat_auth: "ضمان الأصالة", feat_auth_desc: "كل منتج يتم التحقق منه يدوياً قبل وصوله إليك.",
    feat_returns: "إرجاع سهل", feat_returns_desc: "إرجاع بدون متاعب خلال 14 يوماً. بدون أسئلة.",
    foot_tagline: "أساسيات منتقاة لحياة أكثر قصداً.<br/>صنع بفخر في الجزائر.",
    foot_shop: "المتجر", foot_new_arrivals: "جديدنا", foot_best_sellers: "الأكثر مبيعاً",
    foot_home_living: "المنزل والمعيشة", foot_accessories: "إكسسوارات", foot_gift_sets: "علب الهدايا",
    foot_info: "معلومات", foot_our_story: "قصتنا", foot_shipping: "الشحن والإرجاع",
    foot_privacy: "سياسة الخصوصية", foot_terms: "شروط الاستخدام", foot_faq: "الأسئلة الشائعة",
    foot_contact: "اتصل بنا",
    foot_copy: "© 2026 AIZO.DZ — جميع الحقوق محفوظة.", foot_made: "صنع بنية · الجزائر",
    cart_title_ar: "سلة المشتريات", cart_title_en: "/ Cart",
    cart_empty_ar: "السلة فارغة حالياً", cart_empty_en: "سلة التسوق فارغة",
    cart_shop_now: "تسوق الآن",
    cart_subtotal: "المجموع الفرعي", cart_shipping_label: "الشحن", cart_total: "الإجمالي", cart_free: "مجاّني",
    checkout_title_ar: "معلومات التوصيل", checkout_title_en: "/ Delivery Info",
    checkout_name_label: "الاسم *", checkout_name_ph: "الاسم الشخصي",
    checkout_surname_label: "اللقب *", checkout_surname_ph: "اللقب العائلي",
    checkout_phone_label: "رقم الهاتف *", checkout_phone_ph: "05 / 06 / 07 XX XX XX XX",
    checkout_wilaya_label: "الولاية *", checkout_wilaya_ph: "اختر الولاية...",
    checkout_delivery_type: "نوع التوصيل *",
    delivery_home: "التوصيل إلى المنزل (A DOMICILE)", delivery_home_desc: "الدفع عند الاستلام بباب المنزل",
    delivery_office: "التوصيل إلى المكتب (STOP DESK)", delivery_office_desc: "الاستلام من مكتب شركة التوصيل",
    checkout_address_label: "العنوان التفصيلي *",
    checkout_address_ph: "مثال: حي السلام، شارع الأمير، رقم 12، الطابق الثاني",
    checkout_office_label: "مكتب التوصيل *", checkout_office_ph: "اختر مكتب التوصيل...",
    checkout_confirm: "تأكيد الطلب", checkout_sending: "جاري إرسال الطلب...",
    err_name: "يرجى إدخال الاسم", err_surname: "يرجى إدخال اللقب",
    err_phone: "يرجى إدخال رقم هاتف صحيح (10 أرقام)", err_wilaya: "يرجى اختيار الولاية",
    err_address: "يرجى إدخال عنوان المنزل", err_office: "يرجى اختيار مكتب التوصيل",
    success_title: "تم تسجيل طلبك بنجاح!",
    success_subtitle: "شكراً لثقتكم. سنقوم بالاتصال بكم هاتفياً قريباً لتأكيد الطلب وشحنه.",
    success_order_label: "رقم الطلب:", success_name_label: "الاسم:",
    success_phone_label: "الهاتف:", success_wilaya_label: "الولاية:",
    success_delivery_label: "التوصيل إلى:", success_total_label: "المجموع الإجمالي:",
    success_continue: "متابعة التسوق",
    lead_title: "انضم إلينا", lead_desc_ar: "اشترك في قائمتنا البريدية للحصول على آخر التحديثات.",
    lead_placeholder: "بريدك الإلكتروني", lead_subscribe: "اشترك الآن",
    lead_success_title: "شكراً لتسجيلك!", lead_success_desc: "تم تسجيل بريدك بنجاح.",
    marquee_1: "جودة عالية", marquee_2: "توصيل سريع لـ 58 ولاية",
    marquee_3: "منتقاة في الجزائر", marquee_4: "حياة واعية",
    marquee_5: "إرجاع خلال 14 يوم", marquee_6: "ضمان الأصالة",
    coll_hero_title: "المجموعة", coll_hero_desc: "أساسيات بسيطة صُممت بدقة وقصد.",
    coll_search_ph: "اكتب للبحث...", coll_categories: "الفئات",
    coll_all: "جميع المنتجات", coll_denim: "جينز / دينيم", coll_jackets: "جاكيتات", coll_hoodies: "هوديز",
    coll_accessories: "إكسسوارات", coll_shorts: "شورتات", coll_tshirt: "تي شيرت", coll_jorts: "جورتس",
    coll_sort: "ترتيب حسب", coll_featured: "الأكثر رواجاً", coll_price_asc: "السعر: من الأقل",
    coll_price_desc: "السعر: من الأعلى", coll_name_asc: "أ-ي", coll_name_desc: "ي-أ",
    coll_showing: "عرض", coll_products: "منتج",
    pick_color: "اختر اللون", pick_size: "اختر المقاس",
    no_offices: "لا توجد مكاتب توصيل متوفرة في هذه الولاية", choose_office_first: "يرجى اختيار الولاية أولاً...",
    pd_color: "اللون", pd_size: "المقاس", pd_custom_order: "طلب مخصص",
    pd_feat_shipping: "توصيل سريع لـ 58 ولاية", pd_feat_quality: "جودة ممتازة مضمونة",
    pd_feat_returns: "استبدال أو إرجاع خلال 14 يوم",
    co_title: "🎨 تخصيص المنتج الفاخر",
    co_step_design: "التصميم", co_step_options: "الخيارات", co_step_info: "معلومات الزبون", co_step_summary: "الملخص",
    co_area_center: "وسط الصدر", co_area_chest_left: "الصدر يسار", co_area_chest_right: "الصدر يمين",
    co_area_back: "الظهر", co_area_sleeve_right: "الكم الأيمن", co_area_sleeve_left: "الكم الأيسر",
    co_upload: "تحميل التصميم", co_delete: "حذف المحدد", co_garment_color: "لون قطعة الملابس",
    co_size: "المقاس", co_service_type: "نوع الخدمة", co_embroidery: "تطريز", co_print: "طباعة",
    co_active: "مفعل", co_coming_soon: "قريباً",
    co_name: "الاسم الأول *", co_surname: "اللقب *", co_email: "البريد الإلكتروني *", co_phone: "رقم الهاتف *",
    co_province: "الولاية *", co_notes: "ملاحظات إضافية",
    co_order_summary: "ملخص الطلب", co_product: "المنتج", co_placements: "أماكن التصاميم", co_customer: "الزبون",
    co_prev: "← السابق", co_next: "التالي →", co_confirm: "✓ تأكيد الطلب المخصص",
    co_success_title: "تم إرسال طلبك بنجاح!", co_success_desc: "لقد تلقينا طلبك المخصص بنجاح.",
    co_success_close: "إغلاق", co_garment_type: "نوع الملابس",
    co_upload_title: "تحميل تصاميمك (PNG بخلفية شفافة)", co_drag_drop: "اسحب وأسقط شعاراتك هنا",
    co_click_browse: "أو انقر لتصفح الملفات", co_active_designs: "تصاميمي النشطة",
    co_delivery_info_title: "معلومات التوصيل", co_name_ph: "الاسم الأول", co_surname_ph: "اللقب",
    co_email_ph: "مثال: email@example.com", co_phone_ph: "05 / 06 / 07 XX XX XX XX",
    co_notes_ph: "تعليمات خاصة...", co_num_designs: "عدد التصاميم",
    co_summary_desc: "يرجى التحقق من المعلومات أدناه قبل إرسال طلبك.", reviews: "تقييم",
    admin_login_title: "تسجيل الدخول للمشرف", admin_login_desc: "يرجى إدخال الرمز السري.",
    admin_login_pwd_ph: "الرمز السري", admin_login_btn: "دخول لوحة التحكم", admin_back_store: "← العودة إلى المتجر",
    admin_sidebar_role: "مسؤول المتجر", admin_logout: "تسجيل الخروج",
    admin_nav_stats: "✦ الإحصائيات العامة", admin_nav_orders: "📦 إدارة الطلبات",
    admin_nav_custom_orders: "🎨 الطلبات المخصصة", admin_nav_leads: "📧 قائمة الإيميلات",
    admin_nav_add_product: "✨ إضافة منتج جديد", admin_nav_products: "🛍️ قائمة المنتجات",
    admin_profile_status: "لوحة المشرف متصلة", admin_server_disconnected: "الخادم غير متصل",
    admin_login_error: "الرمز السري غير صحيح!",
    admin_back_store_sidebar: "← العودة للمتجر",
    status_pending: "قيد الانتظار", status_confirmed: "مؤكد", status_ready: "جاهز للشحن",
    status_delivery: "قيد التوصيل", status_delivered: "تم التسليم", status_returned: "مُرجع", status_cancelled: "ملغى",
    admin_col_order_id: "رقم الطلب", admin_col_date: "تاريخ الطلب", admin_col_customer: "الزبون",
    admin_col_phone: "الهاتف", admin_col_wilaya: "الولاية", admin_col_delivery: "نوع التوصيل",
    admin_col_items: "المنتجات المطلوبة", admin_col_total: "المجموع", admin_col_status: "الحالة", admin_col_actions: "الإجراءات",
    admin_col_image: "الصورة", admin_col_name: "الاسم", admin_col_category: "الفئة",
    admin_col_price: "السعر", admin_col_badge: "العلامة", admin_col_rating: "التقييم",
    admin_col_sizes: "المقاسات", admin_col_source: "المصدر",
    admin_col_actions_edit: "تعديل", admin_col_actions_delete: "حذف",
    admin_products_empty: "لم يتم تحميل المنتجات بعد.", admin_leads_empty: "لا يوجد مشتركون بعد.",
    admin_orders_empty: "لا توجد طلبات مطابقة.", admin_orders_recent_empty: "لا توجد طلبات مسجّلة بعد.",
    admin_pagination_prev: "السابق", admin_pagination_next: "التالي",
    admin_pagination_page: "الصفحة", admin_pagination_of: "من",
    admin_form_add_title: "إضافة منتج جديد للمتجر", admin_form_btn_save: "حفظ وإضافة المنتج للمتجر",
    admin_form_btn_update: "تحديث وتعديل المنتج", admin_form_btn_reset: "إعادة التعيين",
    admin_form_prod_name: "اسم المنتج *", admin_form_prod_name_ph: "مثال: Vescartes Ronin Jacket",
    admin_form_prod_sub: "الوصف المختصر *", admin_form_prod_sub_ph: "مثال: Edo collection",
    admin_form_prod_price: "السعر (DZD) *", admin_form_prod_img: "رابط صورة المنتج (URL) *",
    admin_form_prod_badge: "علامة المنتج (Badge) - اختياري", admin_form_badge_none: "لا توجد علامة",
    admin_form_prod_stars: "التقييم الافتراضي *", admin_form_prod_reviews: "عدد المراجعات *",
    admin_form_prod_stock: "كمية المخزون *",
    admin_form_prod_colors_chk: "هل يحتوي المنتج على ألوان خيارية؟",
    admin_form_prod_colors: "الألوان المتاحة (افصل بينها بفاصلة) *",
    admin_form_prod_colors_ph: "مثال: أسود, أبيض, أزرق", admin_form_prod_sizes: "المقاسات المتاحة *",
    admin_btn_sync: "🔄 تحديث", admin_btn_delete_order: "🗑️ حذف الطلب",
    admin_btn_ship_zr: "🚀 شحن عبر ZR Express", admin_btn_view_mockup: "🎨 عرض التصميم",
    admin_status_updated: "✓ تم تحديث حالة الطلب بنجاح!", admin_order_deleted: "✓ تم حذف الطلب بنجاح!",
    admin_product_deleted: "✓ تم حذف المنتج بنجاح!", admin_lead_deleted: "✓ تم حذف المشترك بنجاح!",
    admin_order_shipped_zr: "✅ تم الشحن بنجاح عبر ZR Express!",
    admin_order_spec_title: "تفاصيل التصميم المخصص",
    admin_order_spec_color: "اللون:", admin_order_spec_size: "المقاس:", admin_order_spec_service: "الخدمة:",
    admin_order_spec_client: "الزبون:", admin_order_spec_email: "البريد الإلكتروني:", admin_order_spec_phone: "الهاتف:",
    admin_order_spec_province: "الولاية:", admin_order_spec_notes: "ملاحظات:", admin_order_spec_no_notes: "لا توجد ملاحظات",
    admin_order_spec_final_mockup: "معاينة النموذج النهائي", admin_order_spec_files: "ملفات التصاميم المرفقة",
    admin_order_spec_download: "تحميل الملف الأصلي", admin_order_spec_no_files: "لا توجد تصاميم مرفقة",
    admin_src_custom: "مضاف يدوياً", admin_src_default: "افتراضي", admin_no_sizes: "بدون مقاس",
    admin_confirm_delete_order: "هل أنت متأكد من حذف الطلب #{id} نهائياً؟",
    admin_confirm_delete_product: "هل أنت متأكد من حذف هذا المنتج نهائياً؟",
    admin_confirm_delete_lead: "هل أنت متأكد من حذف هذا المشترك؟ {email}",
    admin_confirm_ship_zr: "هل تريد إرسال الطلب #{id} إلى ZR Express للشحن؟",
    admin_error_generic: "حدث خطأ أثناء المعالجة",
    admin_sales_total: "إجمالي المبيعات المؤكدة", admin_orders_total: "إجمالي عدد الطلبات",
    admin_products_active: "عدد المنتجات النشطة", admin_leads_total: "إجمالي المشتركين",
    admin_returned_total: "الطلبات المُرجعة", admin_delivered_total: "الطلبات المسلمة",
    admin_recent_orders: "آخر الطلبات الواردة",
  },
  en: {
    announcement: "FAST SHIPPING 58 WILAYAS & CASH ON DELIVERY",
    nav_new_arrivals: "New Arrivals", nav_collection: "The Collection", nav_about: "About Us",
    nav_dashboard: "Dashboard", nav_shop_now: "Shop Now",
    hero_shop_now: "SHOP NOW",
    cat_shop_by: "Shop by Category", cat_all: "All", cat_jeans: "Jeans",
    cat_jackets: "Jackets", cat_hoodies: "Hoodies",
    cat_accessories: "Accessories", cat_shorts: "Shorts", cat_tshirt: "T-shirt", cat_jorts: "Jorts",
    cat_shop_denim: "Shop Denim", cat_shop_jackets: "Shop Jackets", cat_shop_hoodies: "Shop Hoodies",
    col_eyebrow: "New Arrivals", col_title: "The Collection", col_view_all: "View All →",
    col_load_more: "Load More", col_add_to_cart: "Add to Cart",
    about_eyebrow: "Who we are",
    about_title: "Objects that matter.<br/><em>Moments that last.</em>",
    about_body: "aizo.dz was born from a belief that everyday objects should be beautiful, functional, and intentional.",
    nl_eyebrow: "Stay in the know",
    nl_title: "Join the<br/><em>inner circle.</em>",
    nl_body: "Be the first to hear about new arrivals, exclusive offers, and the stories behind each piece.",
    nl_placeholder: "Your email address", nl_subscribe: "Subscribe",
    nl_success: "✓ Thank you — you're on the list.",
    feat_delivery: "Fast Delivery 58 Wilayas", feat_delivery_desc: "Fast and secure delivery across all wilayas in Algeria.",
    feat_auth: "Authenticity Guarantee", feat_auth_desc: "Every product is hand-verified before it reaches you.",
    feat_returns: "Easy Returns", feat_returns_desc: "14-day hassle-free returns. No questions asked.",
    foot_tagline: "Curated essentials for a more intentional life.<br/>Proudly Algerian.",
    foot_shop: "Shop", foot_new_arrivals: "New Arrivals", foot_best_sellers: "Best Sellers",
    foot_home_living: "Home & Living", foot_accessories: "Accessories", foot_gift_sets: "Gift Sets",
    foot_info: "Info", foot_our_story: "Our Story", foot_shipping: "Shipping & Returns",
    foot_privacy: "Privacy Policy", foot_terms: "Terms of Use", foot_faq: "FAQ", foot_contact: "Contact",
    foot_copy: "© 2026 AIZO.DZ — All rights reserved.", foot_made: "Made with intention · Algeria",
    cart_title_ar: "سلة المشتريات", cart_title_en: "/ Cart",
    cart_empty_ar: "Your cart is empty", cart_empty_en: "Your cart is empty",
    cart_shop_now: "Shop Now",
    cart_subtotal: "Subtotal", cart_shipping_label: "Shipping", cart_total: "Total", cart_free: "Free",
    checkout_title_ar: "Delivery Info", checkout_title_en: "/ Delivery Info",
    checkout_name_label: "First Name *", checkout_name_ph: "First name",
    checkout_surname_label: "Last Name *", checkout_surname_ph: "Last name",
    checkout_phone_label: "Phone Number *", checkout_phone_ph: "05 / 06 / 07 XX XX XX XX",
    checkout_wilaya_label: "State *", checkout_wilaya_ph: "Select state...",
    checkout_delivery_type: "Delivery Type *",
    delivery_home: "Home Delivery (A DOMICILE)", delivery_home_desc: "Cash on delivery at your door",
    delivery_office: "Office Delivery (STOP DESK)", delivery_office_desc: "Pick up from delivery office",
    checkout_address_label: "Home Address *",
    checkout_address_ph: "e.g., Cité la paix, rue de l'émir, n°12, 2nd floor",
    checkout_office_label: "Shipping Office *", checkout_office_ph: "Select office...",
    checkout_confirm: "Confirm Order", checkout_sending: "Sending...",
    err_name: "Please enter first name", err_surname: "Please enter last name",
    err_phone: "Please enter a valid phone number (10 digits)", err_wilaya: "Please select a state",
    err_address: "Please enter home address", err_office: "Please select a shipping office",
    success_title: "Your order has been placed!",
    success_subtitle: "Thank you for your trust. We will contact you soon to confirm and ship your order.",
    success_order_label: "Order #:", success_name_label: "Name:",
    success_phone_label: "Phone:", success_wilaya_label: "State:",
    success_delivery_label: "Delivery to:", success_total_label: "Total:",
    success_continue: "Continue Shopping",
    lead_title: "Join Us", lead_desc_ar: "Subscribe to our newsletter for exclusive collections.",
    lead_placeholder: "Your email address", lead_subscribe: "Subscribe",
    lead_success_title: "Thank You!", lead_success_desc: "Your email has been registered.",
    marquee_1: "Premium Quality", marquee_2: "Fast Delivery 58 Wilayas",
    marquee_3: "Curated in Algeria", marquee_4: "Mindful Living",
    marquee_5: "14-Day Returns", marquee_6: "Authenticity Guaranteed",
    coll_hero_title: "The Collection", coll_hero_desc: "Minimalist essentials designed with precision and intention.",
    coll_search_ph: "Type to search...", coll_categories: "Categories",
    coll_all: "All Products", coll_denim: "Denim / Jeans", coll_jackets: "Jackets", coll_hoodies: "Hoodies",
    coll_accessories: "Accessories", coll_shorts: "Shorts", coll_tshirt: "T-shirt", coll_jorts: "Jorts",
    coll_sort: "Sort By", coll_featured: "Featured", coll_price_asc: "Price: Low to High",
    coll_price_desc: "Price: High to Low", coll_name_asc: "A-Z", coll_name_desc: "Z-A",
    coll_showing: "Showing", coll_products: "products",
    pick_color: "Select Color", pick_size: "Select Size",
    no_offices: "No delivery offices available in this state", choose_office_first: "Please select a state first...",
    pd_color: "Color", pd_size: "Size", pd_custom_order: "Custom Order",
    pd_feat_shipping: "Fast Shipping 58 Wilayas", pd_feat_quality: "Premium Quality Guaranteed",
    pd_feat_returns: "14-Day Returns & Exchanges",
    co_title: "🎨 Premium Customization",
    co_step_design: "Design", co_step_options: "Options", co_step_info: "Customer Info", co_step_summary: "Summary",
    co_area_center: "Center Chest", co_area_chest_left: "Left Chest", co_area_chest_right: "Right Chest",
    co_area_back: "Back", co_area_sleeve_right: "Right Sleeve", co_area_sleeve_left: "Left Sleeve",
    co_upload: "Upload Design", co_delete: "Delete Selected", co_garment_color: "Garment Color",
    co_size: "Garment Size", co_service_type: "Production Method", co_embroidery: "Embroidery", co_print: "Printing",
    co_active: "Active", co_coming_soon: "Soon",
    co_name: "First Name *", co_surname: "Last Name *", co_email: "Email *", co_phone: "Phone Number *",
    co_province: "Wilaya *", co_notes: "Special Notes",
    co_order_summary: "Order Summary", co_product: "Product", co_placements: "Placements", co_customer: "Customer",
    co_prev: "← Previous", co_next: "Next →", co_confirm: "✓ Confirm Custom Order",
    co_success_title: "Order Submitted Successfully!", co_success_desc: "Your custom order has been received.",
    co_success_close: "Close", co_garment_type: "Garment Type",
    co_upload_title: "Upload your designs (Transparent PNG)", co_drag_drop: "Drag & drop your logos here",
    co_click_browse: "Or click to browse files", co_active_designs: "My Active Designs",
    co_delivery_info_title: "Delivery Information", co_name_ph: "First name", co_surname_ph: "Last name",
    co_email_ph: "e.g., email@example.com", co_phone_ph: "05 / 06 / 07 XX XX XX XX",
    co_notes_ph: "Special instructions...", co_num_designs: "Number of designs",
    co_summary_desc: "Please verify the information below before submitting.", reviews: "reviews",
    admin_login_title: "Admin Login", admin_login_desc: "Please enter the password to access the dashboard.",
    admin_login_pwd_ph: "Password", admin_login_btn: "Login to Dashboard", admin_back_store: "← Back to store",
    admin_sidebar_role: "Store Manager", admin_logout: "Log out",
    admin_nav_stats: "✦ Statistics", admin_nav_orders: "📦 Orders",
    admin_nav_custom_orders: "🎨 Custom Orders", admin_nav_leads: "📧 Email List",
    admin_nav_add_product: "✨ Add Product", admin_nav_products: "🛍️ Product List",
    admin_profile_status: "Admin online", admin_server_disconnected: "Server offline",
    admin_login_error: "Incorrect password!",
    admin_back_store_sidebar: "← Back to store",
    status_pending: "Pending", status_confirmed: "Confirmed", status_ready: "Ready to Ship",
    status_delivery: "In Delivery", status_delivered: "Delivered", status_returned: "Returned", status_cancelled: "Cancelled",
    admin_col_order_id: "Order #", admin_col_date: "Date", admin_col_customer: "Customer",
    admin_col_phone: "Phone", admin_col_wilaya: "Wilaya", admin_col_delivery: "Delivery",
    admin_col_items: "Items", admin_col_total: "Total", admin_col_status: "Status", admin_col_actions: "Actions",
    admin_col_image: "Image", admin_col_name: "Name", admin_col_category: "Category",
    admin_col_price: "Price", admin_col_badge: "Badge", admin_col_rating: "Rating",
    admin_col_sizes: "Sizes", admin_col_source: "Source",
    admin_col_actions_edit: "Edit", admin_col_actions_delete: "Delete",
    admin_products_empty: "No products loaded.", admin_leads_empty: "No subscribers yet.",
    admin_orders_empty: "No matching orders.", admin_orders_recent_empty: "No orders registered yet.",
    admin_pagination_prev: "Previous", admin_pagination_next: "Next",
    admin_pagination_page: "Page", admin_pagination_of: "of",
    admin_form_add_title: "Add New Product", admin_form_btn_save: "Save & Add Product",
    admin_form_btn_update: "Update Product", admin_form_btn_reset: "Reset",
    admin_form_prod_name: "Product Name *", admin_form_prod_name_ph: "e.g., Vescartes Ronin Jacket",
    admin_form_prod_sub: "Short Description *", admin_form_prod_sub_ph: "e.g., Edo collection",
    admin_form_prod_price: "Price (DZD) *", admin_form_prod_img: "Product Image URL *",
    admin_form_prod_badge: "Product Badge (Optional)", admin_form_badge_none: "No badge",
    admin_form_prod_stars: "Rating (Stars) *", admin_form_prod_reviews: "Reviews Count *",
    admin_form_prod_stock: "Stock Quantity *",
    admin_form_prod_colors_chk: "Does the product have color options?",
    admin_form_prod_colors: "Available colors (comma separated) *",
    admin_form_prod_colors_ph: "e.g., Black, White, Blue", admin_form_prod_sizes: "Available Sizes *",
    admin_btn_sync: "🔄 Update", admin_btn_delete_order: "🗑️ Delete Order",
    admin_btn_ship_zr: "🚀 Ship via ZR Express", admin_btn_view_mockup: "🎨 View Design",
    admin_status_updated: "✓ Order status updated!", admin_order_deleted: "✓ Order deleted!",
    admin_product_deleted: "✓ Product deleted!", admin_lead_deleted: "✓ Subscriber deleted!",
    admin_order_shipped_zr: "✅ Shipped successfully via ZR Express!",
    admin_order_spec_title: "Custom Order Details",
    admin_order_spec_color: "Color:", admin_order_spec_size: "Size:", admin_order_spec_service: "Service:",
    admin_order_spec_client: "Client:", admin_order_spec_email: "Email:", admin_order_spec_phone: "Phone:",
    admin_order_spec_province: "Wilaya:", admin_order_spec_notes: "Notes:", admin_order_spec_no_notes: "No notes",
    admin_order_spec_final_mockup: "Final Mockup Preview", admin_order_spec_files: "Uploaded Design Files",
    admin_order_spec_download: "Download Original Design", admin_order_spec_no_files: "No design files attached",
    admin_src_custom: "Manually added", admin_src_default: "Default", admin_no_sizes: "No size",
    admin_confirm_delete_order: "Delete order #{id} permanently?",
    admin_confirm_delete_product: "Delete this product permanently?",
    admin_confirm_delete_lead: "Delete this subscriber? {email}",
    admin_confirm_ship_zr: "Send order #{id} to ZR Express for shipping?",
    admin_error_generic: "An error occurred during processing.",
    admin_sales_total: "Confirmed Sales", admin_orders_total: "Total Orders",
    admin_products_active: "Active Products", admin_leads_total: "Total Subscribers",
    admin_returned_total: "Returned Orders", admin_delivered_total: "Delivered Orders",
    admin_recent_orders: "Recent Orders",
  }
}

export const useLangStore = defineStore('lang', () => {
  const lang = ref(localStorage.getItem('aizo_lang') || 'fr')

  const isRTL = computed(() => lang.value === 'ar')
  const dir = computed(() => lang.value === 'ar' ? 'rtl' : 'ltr')
  const t = computed(() => TRANSLATIONS[lang.value] || TRANSLATIONS.fr)

  function setLang(newLang) {
    if (!['ar', 'fr', 'en'].includes(newLang)) return
    lang.value = newLang
    localStorage.setItem('aizo_lang', newLang)
    document.documentElement.lang = newLang
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr'
  }

  function initLang() {
    const saved = localStorage.getItem('aizo_lang') || 'fr'
    setLang(saved)
  }

  function tr(key) {
    return t.value[key] || key
  }

  return { lang, isRTL, dir, t, setLang, initLang, tr }
})
